use_frameworks!

platform :ios, '9.2'

target 'MasqueradeDemo' do
  pod 'Masquerade', path: '../../'
  pod 'Brick', path: '~/Code/Brick'
  pod 'Compass', '~> 4.0'
  pod 'Fashion', '~> 2.0'
  pod 'Spots', path: '~/Code/Spots'
  pod 'Hue', '~> 2.0'
  pod 'Fashion', '~> 2.0'
  pod 'Cartography'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'Spots'
        target.build_configurations.each do |config|
          if config.name == 'Debug'
            config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG -DDEVMODE'
            else
            config.build_settings['OTHER_SWIFT_FLAGS'] = ''
          end
        end
      end
    end
  end
end

